# Generated by Django 4.0.6 on 2022-07-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='room',
            new_name='question',
        ),
    ]
