# Generated by Django 4.0.6 on 2022-08-10 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_answer_name_alter_answer_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='answer_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
